#!/bin/sh

TESTDIR=`pwd`
TEMPDIR=`mktemp --tmpdir -d libunwind-test-XXXXXXXXXX`
trap "rm -r -- $TEMPDIR" EXIT

# create core dump
(
    cd $TEMPDIR
    ulimit -c 10000
    $TESTDIR/crasher $TEMPDIR/backing_files
) 2>/dev/null
COREFILE=$TEMPDIR/core*

# magic option -testcase enables checking for the specific contents of the stack
./test-coredump-unwind $COREFILE -testcase `cat $TEMPDIR/backing_files`
