/* libunwind - a platform-independent unwind library
   Copyright (C) 2014 Oracle Inc
   Contributed by
     Jose E. Marchesi <jose.marchesi@oracle.com>

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.  */

#ifndef ucontext_i_h
#define ucontext_i_h

#include <ucontext.h>

/* These values were derived from the linux kernel sources.  */

#define NIP_IDX		32
#define MSR_IDX		33
#define ORIG_GPR3_IDX	34
#define CTR_IDX		35
#define LINK_IDX	36
#define XER_IDX		37
#define CCR_IDX		38
#define SOFTE_IDX	39
#define TRAP_IDX	40
#define DAR_IDX		41
#define DSISR_IDX	42
#define RESULT_IDX	43

#define VSCR_IDX        32
#define VRSAVE_IDX      33

/* These are dummy structures used only for obtaining the offsets of the
   various structure members. */
static ucontext_t dmy_ctxt;

#define DMY_GREGS_OFFSET(OFFSET) \
  ((void *)&dmy_ctx.uc_mcontext.mc_gregs[(OFFSET)] - (void *)&dmy_ctxt)
#define DMY_FPREGS_OFFSET(OFFSET) \
  ((void *)&dmy_ctx.uc_mcontext.mc_fpregs.mfpu_fregs.sregs[(OFFSET)] - (void*)&dmy_ctxt)

#define UC_MCONTEXT_GREGS_TSTATE DMY_GREGS_OFFSET(MC_TSTATE)
#define UC_MCONTEXT_GREGS_PC     DMY_GREGS_OFFSET(MC_PC)
#define UC_MCONTEXT_GREGS_NPC    DMY_GREGS_OFFSET(MC_Y)
#define UC_MCONTEXT_GREGS_G1     DMY_GREGS_OFFSET(MC_G1)
#define UC_MCONTEXT_GREGS_G2     DMY_GREGS_OFFSET(MC_G2)
#define UC_MCONTEXT_GREGS_G3     DMY_GREGS_OFFSET(MC_G3)
#define UC_MCONTEXT_GREGS_G4     DMY_GREGS_OFFSET(MC_G4)
#define UC_MCONTEXT_GREGS_G5     DMY_GREGS_OFFSET(MC_G5)
#define UC_MCONTEXT_GREGS_G6     DMY_GREGS_OFFSET(MC_G6)
#define UC_MCONTEXT_GREGS_G7     DMY_GREGS_OFFSET(MC_G7)
#define UC_MCONTEXT_GREGS_O0     DMY_GREGS_OFFSET(MC_O0)
#define UC_MCONTEXT_GREGS_O1     DMY_GREGS_OFFSET(MC_O1)
#define UC_MCONTEXT_GREGS_O2     DMY_GREGS_OFFSET(MC_O2)
#define UC_MCONTEXT_GREGS_O3     DMY_GREGS_OFFSET(MC_O3)
#define UC_MCONTEXT_GREGS_O4     DMY_GREGS_OFFSET(MC_O4)
#define UC_MCONTEXT_GREGS_O5     DMY_GREGS_OFFSET(MC_O5)
#define UC_MCONTEXT_GREGS_O6     DMY_GREGS_OFFSET(MC_O6)
#define UC_MCONTEXT_GREGS_O7     DMY_GREGS_OFFSET(MC_O7)

#define UC_MCONTEXT_FPREGS_F0     DMY_FPREGS_OFFSET(0)
#define UC_MCONTEXT_FPREGS_F1     DMY_FPREGS_OFFSET(1)
#define UC_MCONTEXT_FPREGS_F2     DMY_FPREGS_OFFSET(2)
#define UC_MCONTEXT_FPREGS_F3     DMY_FPREGS_OFFSET(3)
#define UC_MCONTEXT_FPREGS_F4     DMY_FPREGS_OFFSET(3)
#define UC_MCONTEXT_FPREGS_F5     DMY_FPREGS_OFFSET(3)
#define UC_MCONTEXT_FPREGS_F6     DMY_FPREGS_OFFSET(3)
#define UC_MCONTEXT_FPREGS_F7     DMY_FPREGS_OFFSET(3)
#define UC_MCONTEXT_FPREGS_F8     DMY_FPREGS_OFFSET(3)
#define UC_MCONTEXT_FPREGS_F9     DMY_FPREGS_OFFSET(3)
#define UC_MCONTEXT_FPREGS_F10    DMY_FPREGS_OFFSET(3)
#define UC_MCONTEXT_FPREGS_F11    DMY_FPREGS_OFFSET(3)
#define UC_MCONTEXT_FPREGS_F12    DMY_FPREGS_OFFSET(3)
#define UC_MCONTEXT_FPREGS_F13    DMY_FPREGS_OFFSET(3)
#define UC_MCONTEXT_FPREGS_F14    DMY_FPREGS_OFFSET(3)
#define UC_MCONTEXT_FPREGS_F15    DMY_FPREGS_OFFSET(3)
#define UC_MCONTEXT_FPREGS_F16    DMY_FPREGS_OFFSET(16)
#define UC_MCONTEXT_FPREGS_F17    DMY_FPREGS_OFFSET(17)
#define UC_MCONTEXT_FPREGS_F18    DMY_FPREGS_OFFSET(18)
#define UC_MCONTEXT_FPREGS_F19    DMY_FPREGS_OFFSET(19)
#define UC_MCONTEXT_FPREGS_F20    DMY_FPREGS_OFFSET(20)
#define UC_MCONTEXT_FPREGS_F21    DMY_FPREGS_OFFSET(21)
#define UC_MCONTEXT_FPREGS_F22    DMY_FPREGS_OFFSET(22)
#define UC_MCONTEXT_FPREGS_F23    DMY_FPREGS_OFFSET(23)
#define UC_MCONTEXT_FPREGS_F24    DMY_FPREGS_OFFSET(24)
#define UC_MCONTEXT_FPREGS_F25    DMY_FPREGS_OFFSET(25)
#define UC_MCONTEXT_FPREGS_F26    DMY_FPREGS_OFFSET(26)
#define UC_MCONTEXT_FPREGS_F27    DMY_FPREGS_OFFSET(27)
#define UC_MCONTEXT_FPREGS_F28    DMY_FPREGS_OFFSET(28)
#define UC_MCONTEXT_FPREGS_F29    DMY_FPREGS_OFFSET(29)
#define UC_MCONTEXT_FPREGS_F30    DMY_FPREGS_OFFSET(30)
#define UC_MCONTEXT_FPREGS_F31    DMY_FPREGS_OFFSET(31)
#define UC_MCONTEXT_FPREGS_F32    DMY_FPREGS_OFFSET(32)
#define UC_MCONTEXT_FPREGS_F33    DMY_FPREGS_OFFSET(33)
#define UC_MCONTEXT_FPREGS_F34    DMY_FPREGS_OFFSET(34)
#define UC_MCONTEXT_FPREGS_F35    DMY_FPREGS_OFFSET(35)
#define UC_MCONTEXT_FPREGS_F36    DMY_FPREGS_OFFSET(36)
#define UC_MCONTEXT_FPREGS_F37    DMY_FPREGS_OFFSET(37)
#define UC_MCONTEXT_FPREGS_F38    DMY_FPREGS_OFFSET(38)
#define UC_MCONTEXT_FPREGS_F39    DMY_FPREGS_OFFSET(39)
#define UC_MCONTEXT_FPREGS_F40    DMY_FPREGS_OFFSET(40)
#define UC_MCONTEXT_FPREGS_F41    DMY_FPREGS_OFFSET(41)
#define UC_MCONTEXT_FPREGS_F42    DMY_FPREGS_OFFSET(42)
#define UC_MCONTEXT_FPREGS_F43    DMY_FPREGS_OFFSET(43)
#define UC_MCONTEXT_FPREGS_F44    DMY_FPREGS_OFFSET(44)
#define UC_MCONTEXT_FPREGS_F45    DMY_FPREGS_OFFSET(45)
#define UC_MCONTEXT_FPREGS_F46    DMY_FPREGS_OFFSET(46)
#define UC_MCONTEXT_FPREGS_F47    DMY_FPREGS_OFFSET(47)
#define UC_MCONTEXT_FPREGS_F48    DMY_FPREGS_OFFSET(48)
#define UC_MCONTEXT_FPREGS_F49    DMY_FPREGS_OFFSET(49)
#define UC_MCONTEXT_FPREGS_F50    DMY_FPREGS_OFFSET(50)
#define UC_MCONTEXT_FPREGS_F51    DMY_FPREGS_OFFSET(51)
#define UC_MCONTEXT_FPREGS_F52    DMY_FPREGS_OFFSET(52)
#define UC_MCONTEXT_FPREGS_F53    DMY_FPREGS_OFFSET(53)
#define UC_MCONTEXT_FPREGS_F54    DMY_FPREGS_OFFSET(54)
#define UC_MCONTEXT_FPREGS_F55    DMY_FPREGS_OFFSET(55)
#define UC_MCONTEXT_FPREGS_F56    DMY_FPREGS_OFFSET(56)
#define UC_MCONTEXT_FPREGS_F57    DMY_FPREGS_OFFSET(57)
#define UC_MCONTEXT_FPREGS_F58    DMY_FPREGS_OFFSET(58)
#define UC_MCONTEXT_FPREGS_F59    DMY_FPREGS_OFFSET(59)
#define UC_MCONTEXT_FPREGS_F60    DMY_FPREGS_OFFSET(60)
#define UC_MCONTEXT_FPREGS_F61    DMY_FPREGS_OFFSET(61)
#define UC_MCONTEXT_FPREGS_F62    DMY_FPREGS_OFFSET(62)
#define UC_MCONTEXT_FPREGS_F63    DMY_FPREGS_OFFSET(63)

#endif
