name: CI - Linux - MUSL

permissions:
  contents: read

on:
  pull_request:
    paths:
      - '**'
      - '!README'
      - '!INSTALL'
      - '!NEWS'
      - '!doc/**'
      - '!.**'
      - '.github/workflows/CI-linux-musl.yml'
  push:
    branches:
      - v[0-9].*
      - master

jobs:
  build-musl-native:
    runs-on: ubuntu-latest
    timeout-minutes: 15 # Anything more than about 15 minutes is likely a testsuite hang.
    name: ${{ matrix.arch }}-linux-musl (native)

    strategy:
      fail-fast: false
      matrix:
        arch: [aarch64, ppc64le, riscv64, x86_64]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Alpine Linux
        uses: jirutka/setup-alpine@ae3b3ddba35054804fc4a3507b519fa7e8152050 # v1.4.1
        with:
          branch: edge
          arch: ${{ matrix.arch }}
          packages: >
            autoconf 
            automake 
            build-base 
            libtool 
            libucontext-dev
            linux-headers
            xz-dev
          shell-name: alpine.sh

      - name: Configure
        run: |
          set -x
          gcc --version
          autoreconf -i
          ./configure --enable-debug
        env:
          CFLAGS: -g -O0 -Wall -Wextra
          CXXFLAGS: -g -O0
          LDFLAGS: -g -O0
        shell: alpine.sh {0}

      - name: Build
        run: |
          make -j
        shell: alpine.sh {0}

      - name: Test
        if: ${{ success() }}
        run: |
          make check
        env:
          UNW_DEBUG_LEVEL: 5
        shell: alpine.sh {0}

      - name: Upload Test Logs
        # This step only runs if the "Build and Test" step fails
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: logs-${{ matrix.arch }}-linux-musl
          path: '**/test-suite.log'
          if-no-files-found: warn
